from app.db.schema import CandidateHealth
from app.db.operational_session import operational_engine
from sqlmodel import Session, select, text


def test_reset_candidate_health(client):
    # Setup: Create a disabled candidate
    with Session(operational_engine) as session:
        session.execute(text("DELETE FROM candidatehealth"))
        session.commit()

        # We need a candidate hash. Let's just create one manually.
        # In real usage, this is generated by calculate_candidate_hash
        health = CandidateHealth(
            candidate_hash="test-hash",
            provider_id=1,
            key_id=None,
            model="test-model",
            failure_count=10,
        )
        session.add(health)
        session.commit()

    # Action: Reset health
    response = client.post("/api/settings/reset-health")
    assert response.status_code == 200
    assert "success" in response.json()["status"]

    # Verification: check that CandidateHealth table is empty (per implementation)
    with Session(operational_engine) as session:
        results = session.exec(select(CandidateHealth)).all()
        assert len(results) == 0
